version: "3.1"
services: 
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:      
      MONGO_INITDB_DATABASE: graphql_books 
    volumes: 
      - gqlbooks_data:/var/lib/mysql  
volumes: 
  gqlbooks_data:
