version: '3.4'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    # environment: 
    #   RABBITMQ_USERNAME: app
    #   RABBITMQ_PASSWORD: appPassw0rd 
    # Default username and password is `user` and `bitnami`
volumes:
  rabbitmq_data:
    driver: local
